### PR TITLE
Fix compilation errors with 2 examples that use icons.

### PR DESCRIPTION
**Pull request by hydra**
Compilation looks like it was broken by 7d14e42d117a76a2e20bd88bf29117bd4745d2a3

Icons were moved to `iced_fonts` according to the changelog, but it looks like these two examples were missed.

Note: It appears that neither `sidebar` or `tab_bar` examples are compiled when running `cargo build --examples`.

I also note there's no `Build: Passing/Failed` badge for this repo or automated github actions which would likely have highlighted this compilation error earlier.

### CODE REVIEW

**Review by genusistimelord — APPROVED** [review]
thank you! good catch.
